# Generated by `make macos-cask` in the vazifedar repo — do not edit by hand,
# the next release overwrites this file. Version and checksum are filled in
# from the DMG that was just notarized and published.
cask "vazifedar" do
  version "0.0.7"
  sha256 "7c7dc4d2724e172cf108bbdc0299cc645509ba290dd0f2689230163a7bff9e96"

  url "https://github.com/hayrat/homebrew-vazifedar/releases/download/macos-#{version}/Vazifedar.dmg",
      verified: "github.com/hayrat/homebrew-vazifedar/"
  name "Vazifedar"
  desc "Kurum ici gorev atama ve takip"
  homepage "https://github.com/hayrat/homebrew-vazifedar"

  livecheck do
    url :url
    strategy :github_latest
    regex(/^macos[._-]v?(\d+(?:\.\d+)+)$/i)
  end

  # Plain symbol, not ">= :tahoe": the string-comparison form is deprecated and
  # a bare symbol already means "this version or newer". Matches the project's
  # macOS 26.0 deployment target — the UI is built on `.glassEffect`, which
  # shipped with macOS 26, so there is no older build to fall back to.
  depends_on macos: :tahoe

  app "Vazifedar.app"

  # The app is no longer sandboxed (it updates itself — see macos/CLAUDE.md), so
  # preferences and caches sit in the usual per-bundle-id places. The container
  # path stays in the list for anyone who first installed 0.0.1, which was
  # sandboxed. Keychain items (the auth tokens) are deliberately left alone —
  # zap must not touch a keychain the user may share with other machines.
  zap trash: [
    "~/Library/Preferences/com.hayteknoloji.vazifedar.plist",
    "~/Library/Caches/com.hayteknoloji.vazifedar",
    "~/Library/HTTPStorages/com.hayteknoloji.vazifedar",
    "~/Library/Saved Application State/com.hayteknoloji.vazifedar.savedState",
    "~/Library/Containers/com.hayteknoloji.vazifedar",
  ]
end
