# Generated by `make macos-cask` in the vazifedar repo — do not edit by hand,
# the next release overwrites this file. Version and checksum are filled in
# from the DMG that was just notarized and published.
cask "vazifedar" do
  version "0.0.4"
  sha256 "c5539bb2476eab1e5bb8a8d2c268e400bfd98d1418ac495daf5dc401df99619c"

  url "https://github.com/hayrat/homebrew-vazifedar/releases/download/macos-#{version}/Vazifedar.dmg",
      verified: "github.com/hayrat/homebrew-vazifedar/"
  name "Vazifedar"
  desc "Kurum ici gorev atama ve takip"
  homepage "https://github.com/hayrat/homebrew-vazifedar"

  livecheck do
    url :url
    strategy :github_latest
    regex(/^macos[._-]v?(\d+(?:\.\d+)+)$/i)
  end

  # Plain symbol, not ">= :sonoma": the string-comparison form is deprecated and
  # a bare symbol already means "this version or newer". Matches the project's
  # macOS 14.0 deployment target.
  depends_on macos: :sonoma

  app "Vazifedar.app"

  # The app is no longer sandboxed (it updates itself — see macos/CLAUDE.md), so
  # preferences and caches sit in the usual per-bundle-id places. The container
  # path stays in the list for anyone who first installed 0.0.1, which was
  # sandboxed. Keychain items (the auth tokens) are deliberately left alone —
  # zap must not touch a keychain the user may share with other machines.
  zap trash: [
    "~/Library/Preferences/com.hayteknoloji.vazifedar.plist",
    "~/Library/Caches/com.hayteknoloji.vazifedar",
    "~/Library/HTTPStorages/com.hayteknoloji.vazifedar",
    "~/Library/Saved Application State/com.hayteknoloji.vazifedar.savedState",
    "~/Library/Containers/com.hayteknoloji.vazifedar",
  ]
end
